name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }} # Your server's IP or domain
        username: ${{ secrets.SERVER_USER }} # SSH username
        key: ${{ secrets.SERVER_PRIVATE_KEY }} # Private SSH key
        script: |
          PID=$(lsof -t -i :$5000)
          if [ -z "$PID" ]; then
            echo "No process found running on port"
          else
            echo "Killing process $PID running on port..."
            kill -9 $PID
            echo "Process $PID has been terminated."
          fi
          rm -rf ./MeirFriedmann.github.io/
          git clone https://github.com/meirfriedmann/MeirFriedmann.github.io.git
          node ./MeirFriedmann.github.io/backend/server.js
