name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code
      - name: Set up SSH agent
        run: |
          eval $(ssh-agent)
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" | ssh-add -

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_ed25519  # Add private key to the runner
          chmod 600 ~/.ssh/id_ed25519  # Set correct permissions for private key
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts  # Add your server to known hosts

      - name: Copy deploy script to remote server
        run: |
          scp deploy.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/deploy.sh 
  
      - name: Execute on remote Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "bash /tmp/deploy.sh"